language: node_js
env:
  global:
    - NODE_ENV=TEST
    - TZ=Asia/Tokyo
node_js:
  - "lts/*"
services:
  - docker
cache:
  - "node_modules"
before_install:
  - date
  - touch .env.dev
  - sh script/ci.sh
install:
  - npm i -g npx
  - npm i
before_script:
  - sh script/setup_local_db.sh
script:
  - npm test