language: node_js
env:
  global:
    - NODE_ENV=TEST
node_js:
  - "lts/*"
services:
  - docker
cache:
  - "node_modules"
before_install:
  - touch .env.dev
  - sh script/ci.sh
install:
  - npm i -g npx
  - npm i
before_script:
  - echo 'Asia/Japan' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - date
  - sh script/setup_local_db.sh
script:
  - npm test