service: hiyoko-sensei
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:NODE_ENV}  # Set the default stage used. Default is dev
  region: ap-northeast-1 # Overwrite the default region used. Default is us-east-1
  environment:
    NODE_ENV: ${env:NODE_ENV}
    LINE_BOT_ACCESS_TOKEN: ${env:LINE_BOT_ACCESS_TOKEN}
    LINE_BOT_SECRET_TOKEN: ${env:LINE_BOT_SECRET_TOKEN}
    CORE_URL: ${env:CORE_URL}
    ADMIN_TOKEN: ${env:ADMIN_TOKEN}
plugins:
  - serverless-plugin-typescript
functions:
  # For bot
  hiyokoSensei:
    handler: src/hiyokoMantle/web/bot/index.handler
    events:
      - http:
          path: hiyokoSensei/bot/webhook
          method: post
          cors: true
  # For add vocabulary
  hiyokoSenseiLiff:
    handler: src/hiyokoMantle/web/liff/vocabularyListAdd.handler
    events:
      - http:
          path: hiyokoSensei/liff/vocabularyList/add
          method: get
          cors: true
      - http:
          path: hiyokoSensei/liff/vocabularyList/add
          method: post
          cors: true
  # For list all user vocabularies
  hiyokoSenseiLiff-Vocabularies:
    handler: src/hiyokoMantle/web/liff/vocabularyLists.handler
    events:
      - http:
          path: hiyokoSensei/liff/vocabularyLists/all
          method: get
          cors: true
      - http:
          path: hiyokoSensei/api/vocabularyLists
          method: get
          cors: true
      - http:
          path: hiyokoSensei/api/vocabularyLists
          method: delete
          cors: true
  # For simple quizzes
  hiyokoSenseiLiff-SimpleQuizzes:
    handler: src/hiyokoMantle/web/liff/simpleQuizzes.handler
    events:
      - http:
          path: hiyokoSensei/liff/quizzes/simple
          method: get
          cors: true
      - http:
          path: hiyokoSensei/api/quizzes/simple
          method: get
          cors: true
      - http:
          path: hiyokoSensei/api/quizzes/simple
          method: post
          cors: true
  # For composite quizzes
  hiyokoSenseiLiff-CompositeQuizzes:
    handler: src/hiyokoMantle/web/liff/compositeQuizzes.handler
    events:
      - http:
          path: hiyokoSensei/liff/quizzes/composite
          method: get
          cors: true
      - http:
          path: hiyokoSensei/api/quizzes/composite
          method: get
          cors: true
      - http:
          path: hiyokoSensei/api/quizzes/composite
          method: post
          cors: true
  hiyokoSenseiLiff-UserSetting:
    handler: src/hiyokoMantle/web/liff/userSetting.handler
    events:
      - http:
          path: hiyokoSensei/liff/userSetting/home
          method: get
          cors: true
      - http:
          path: hiyokoSensei/liff/userSetting/planning
          method: get
          cors: true
  # For push message
  # FIXME: This setting makes two pushers(DEV / PROD)
  hiyokoSenseiPusher:
    handler: src/hiyokoMantle/web/pusher/index.handler
    events:
      - http:
          path: hiyokoSensei/pusher/message/users
          method: post
          cors: true
      - http:
          path: hiyokoSensei/pusher/message/users/all
          method: post
          cors: true
package:
  include:
    - src/hiyokoMantle/web/liff/template
  exclude:
    - src/hiyokoCore
    - build
    - db
    - prac