service: hiyoko-sensei
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:NODE_ENV}  # Set the default stage used. Default is dev
  region: ap-northeast-1 # Overwrite the default region used. Default is us-east-1
  environment:
    NODE_ENV: ${env:NODE_ENV}
    LINE_BOT_ACCESS_TOKEN: ${env:LINE_BOT_ACCESS_TOKEN}
    LINE_BOT_SECRET_TOKEN: ${env:LINE_BOT_SECRET_TOKEN}
    CORE_URL: ${env:CORE_URL}
plugins:
  - serverless-plugin-typescript
functions:
  # For bot
  hiyokoSensei:
    handler: src/hiyokoMantle/web/bot/index.handler
    events:
      - http:
          path: hiyokoSensei/bot/webhook
          method: post
          cors: true
  # For add vocabulary
  hiyokoSenseiLiff:
    handler: src/hiyokoMantle/web/liff/vocabularyListAdd.handler
    events:
      - http:
          path: hiyokoSensei/liff/vocabularyList/add
          method: get
          cors: true
      - http:
          path: hiyokoSensei/liff/vocabularyList/add
          method: post
          cors: true
  # For list all user vocabularies
  hiyokoSenseiLiff-Vocabularies:
    handler: src/hiyokoMantle/web/liff/vocabularyLists.handler
    events:
      - http:
          path: hiyokoSensei/liff/vocabularyLists/all
          method: get
          cors: true
      - http:
          path: hiyokoSensei/api/vocabularyLists
          method: get
          cors: true
      - http:
          path: hiyokoSensei/api/vocabularyLists
          method: delete
          cors: true
package:
  include:
    - src/hiyokoMantle/web/liff/template