version: '3.1'
services:
  # web:
  #   build: .
  #   container_name: "omt-project"
  #   ports:
  #     - "19000:9000"
  #   volumes:
  #     - .:/ts/hiyoko-teacher
  #   env_file:
  #     - .env_dev
  #   environment:
  #     - NODE_ENV=DEV
  db:
    image: mysql:5.7.23
    container_name: "mysql"
    ports:
      - "13306:3306"
    volumes:
      - ./../../db:/docker-entrypoint-initdb.d
    # env_file:
    #   - .env_dev
    environment:
      - NODE_ENV=DEV
      - MYSQL_DATABASE=Hiyoko_core
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
