version: '3.1'
services:
  web:
    build:
      context: ../../
      dockerfile: Dockerfile
    links:
      - "db:db"
      - "LogDb:LogDb"
    container_name: "hiyoko-teacher"
    ports:
      - "13000:3000"
    volumes:
      - ../../:/ts/hiyoko-teacher
    env_file:
      - ../../.env.dev
    environment:
      - NODE_ENV=DEV
  db:
    image: mysql:5.7.23
    container_name: "mysql"
    ports:
      - "13306:3306"
    volumes:
      - ./../../db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=Hiyoko_core
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  LogDb:
    image: amazon/dynamodb-local
    container_name: "dynamodb"
    ports:
      - "18000:8000"