version: '3.1'
services:
  web:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: "hiyoko-teacher"
    volumes:
      - ../../:/ts/hiyoko-teacher
    env_file:
      - ../../.env.dev
    environment:
      - NODE_ENV=DEV
  db:
    image: mysql:5.7.23
    container_name: "mysql"
    ports:
      - "13306:3306"
    volumes:
      - ./../../db:/docker-entrypoint-initdb.d
    env_file:
      - ../../.env.dev
